/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pyohwan' at '15. 7. 30 오후 2:40' with Gradle 2.5
 *
 * @author pyohwan, @date 15. 7. 30 오후 2:40
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
